// Microsite renderer (WP4) — turns a brand-profile + the engine's styling snippet into a full
// standalone HTML page: a brand-skinned stepper that embeds <jumio-sdk> at the IDV step.
// Zero dependencies — runs in the browser and in Node.

import { buildHtml } from '../engine/brand-to-theme.mjs';

/** "Acme Bank" -> "acme-bank" */
export function slugify(name) {
  return String(name ?? 'brand')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'brand';
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

function stepperHtml(steps, idvStepIndex) {
  return steps
    .map((label, i) => {
      const state = i === idvStepIndex ? 'is-active' : i < idvStepIndex ? 'is-done' : '';
      return `      <li class="step ${state}"><span class="step__index">${i + 1}</span><span class="step__label">${escapeHtml(label)}</span></li>`;
    })
    .join('\n');
}

/** Pulsing placeholder blocks shown at the IDV step before <jumio-sdk> is mounted. */
function skeletonHtml() {
  return `<div class="jumio-sdk-skeleton" aria-hidden="true">
        <div class="skeleton-line skeleton-line--title"></div>
        <div class="skeleton-line"></div>
        <div class="skeleton-line skeleton-line--short"></div>
        <div class="skeleton-block"></div>
      </div>`;
}

const skeletonStyle = `
    .jumio-sdk-skeleton { display: flex; flex-direction: column; gap: 0.6em; padding: 1em 0; }
    .skeleton-line, .skeleton-block {
      border-radius: 6px;
      background: linear-gradient(90deg,
        var(--jumio-sdk-color-primary1, #e5e7eb) 25%,
        var(--jumio-sdk-color-primary2, #f3f4f6) 50%,
        var(--jumio-sdk-color-primary1, #e5e7eb) 75%);
      background-size: 200% 100%;
      animation: jumio-sdk-skeleton-pulse 1.4s ease-in-out infinite;
    }
    .skeleton-line { height: 0.9em; }
    .skeleton-line--title { width: 60%; height: 1.2em; }
    .skeleton-line--short { width: 40%; }
    .skeleton-block { height: 10em; }
    @keyframes jumio-sdk-skeleton-pulse {
      0% { background-position: 200% 0; }
      100% { background-position: -200% 0; }
    }`;

/**
 * brand-profile -> full microsite HTML page (string).
 * The IDV step shows a themed skeleton with a "Start verification" button; clicking it mounts
 * <jumio-sdk> with the engine's generated theming dropped into <head>/<body>.
 *
 * @param {object} profile - brand-profile.json contents
 * @param {object} [sdkAssets] - paths to the @jumio/websdk runtime (default: vendored at /vendor/websdk/
 *   via `npm run vendor:websdk`, served by Vite's public/ dir and microsite/serve.mjs)
 * @param {string} [sdkAssets.script] - index.js (the SDK entry, type=module)
 * @param {string} [sdkAssets.modulePreload] - optional: the hashed chunk referenced by index.js
 *   (just a perf hint — index.js imports it itself, so this can be omitted)
 * @param {string} [sdkAssets.style] - assets/style.css
 * @param {object} [session] - { dc, token } for the <jumio-sdk> element
 * @param {object} [opts]
 * @param {boolean} [opts.started] - if true, render <jumio-sdk> directly instead of the skeleton
 */
export function renderMicrosite(profile, sdkAssets = {}, session = {}, opts = {}) {
  const brand = profile.brand ?? {};
  const journey = profile.journey ?? {};
  const steps = journey.steps?.length ? journey.steps : ['Create account', 'Verify identity', 'Done'];
  const idvStepIndex = journey.idvStepIndex ?? Math.min(1, steps.length - 1);
  const ctaLabel = journey.ctaLabel ?? 'Verify your identity';
  const themeSnippet = buildHtml(profile);

  return `<!DOCTYPE html>
<html lang="${escapeHtml(profile.sdk?.locale ?? 'en')}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(brand.name ?? 'Brand')} — Onboarding</title>

  <!-- @jumio/websdk runtime, vendored to /vendor/websdk — see scripts/vendor-websdk.mjs -->
  <script type="module" crossorigin src="${escapeHtml(sdkAssets.script ?? '/vendor/websdk/index.js')}"></script>
  ${sdkAssets.modulePreload ? `<link rel="modulepreload" crossorigin href="${escapeHtml(sdkAssets.modulePreload)}" />` : ''}
  <link rel="stylesheet" crossorigin href="${escapeHtml(sdkAssets.style ?? '/vendor/websdk/assets/style.css')}" />

  <!-- Generated by the theming engine (WP3) from brand-profile.json -->
${themeSnippet.split('\n').map((l) => '  ' + l).join('\n')}

  <style>
    :root { --radius: ${escapeHtml(brand.radius ?? '12px')}; }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: var(--jumio-sdk-font-family, system-ui, sans-serif);
      color: var(--jumio-sdk-theme-light-text-color, #111418);
      background: var(--jumio-sdk-theme-light-page-bg-color, #fff);
    }
    header { padding: 1.5em 1em; display: flex; align-items: center; gap: 0.75em; }
    header img { height: 32px; }
    .stepper { list-style: none; display: flex; gap: 0.5em; padding: 0 1em; margin: 0 0 1.5em; }
    .step {
      flex: 1; text-align: center; padding: 0.75em 0.5em; border-radius: var(--radius);
      background: var(--jumio-sdk-theme-light-app-container-bg-color, #f5f7fa);
      font-size: 0.85em; opacity: 0.6;
    }
    .step.is-active { opacity: 1; outline: 2px solid var(--jumio-sdk-color-primary4, #0a7d33); }
    .step.is-done { opacity: 0.85; }
    .step__index {
      display: inline-flex; align-items: center; justify-content: center;
      width: 1.5em; height: 1.5em; border-radius: 50%; margin-right: 0.4em;
      background: var(--jumio-sdk-color-primary4, #0a7d33);
      color: var(--jumio-sdk-theme-light-clickable-primary-default-color, #fff);
      font-weight: 600;
    }
    main {
      width: 90%; max-width: none; margin: 0 auto;
      padding: ${escapeHtml(profile.layout?.containerPadding?.top ?? '2em')} ${escapeHtml(profile.layout?.containerPadding?.right ?? '1em')} ${escapeHtml(profile.layout?.containerPadding?.bottom ?? '2em')} ${escapeHtml(profile.layout?.containerPadding?.left ?? '1em')};
      background: var(--jumio-sdk-theme-light-app-container-bg-color, #f5f7fa);
      border-radius: var(--radius);
    }
    h1 { font-size: 1.25em; margin-top: 0; }
    .cta { color: var(--jumio-sdk-color-primary6, #075423); font-weight: 600; }
    jumio-sdk { display: block; width: 100%; min-height: 640px; margin-top: 1em; }
    .start-verification {
      font: inherit; font-weight: 600; cursor: pointer; border: none; border-radius: var(--radius);
      padding: 0.7em 1.2em; margin-top: 1em;
      background: var(--jumio-sdk-color-primary4, #0a7d33);
      color: var(--jumio-sdk-theme-light-clickable-primary-default-color, #fff);
    }
${skeletonStyle}
  </style>
</head>
<body>
  <header>
    ${brand.logo ? `<img src="${escapeHtml(brand.logo)}" alt="${escapeHtml(brand.name ?? '')}" />` : ''}
    <strong>${escapeHtml(brand.name ?? 'Brand')}</strong>
  </header>

  <ol class="stepper">
${stepperHtml(steps, idvStepIndex)}
  </ol>

  <main>
${steps
    .map((label, i) => {
      if (i !== idvStepIndex) {
        return `    <section data-step="${i}" hidden><h1>${escapeHtml(label)}</h1></section>`;
      }
      const jumioSdkHtml = `<!-- TODO: replace with a real pre-created session token (see ARCHITECTURE.md). -->
      <jumio-sdk dc="${escapeHtml(session.dc ?? 'us')}" token="${escapeHtml(session.token ?? 'REPLACE_WITH_SESSION_TOKEN')}" locale="${escapeHtml(session.locale || profile.sdk?.locale || 'en')}"></jumio-sdk>`;

      return `    <section data-step="${i}">
      <h1>${escapeHtml(label)}</h1>
      <p class="cta">${escapeHtml(ctaLabel)}</p>

${opts.started
        ? `      ${jumioSdkHtml}`
        : `      <div id="jumio-sdk-mount">${skeletonHtml()}</div>
      <button type="button" class="start-verification" id="start-verification">Start verification</button>
      <script>
        document.getElementById('start-verification').addEventListener('click', () => {
          document.getElementById('jumio-sdk-mount').outerHTML = \`${jumioSdkHtml.replace(/`/g, '\\`')}\`;
          document.getElementById('start-verification').remove();
        });
      </script>`}
    </section>`;
    })
    .join('\n')}
  </main>
</body>
</html>
`;
}
